<template>
  <AppLayout page-title="Fiche de soins">
    <div class="hero-gradient mb-8"><p class="eyebrow">PARCOURS DE SOINS</p><h1>Préparer ma fiche de soins</h1><p>Les informations connues sont préremplies. Vous complétez uniquement la partie patient, puis le médecin termine la fiche.</p></div>
    <div v-if="message" class="alert" :class="error ? 'alert-error' : 'alert-success'">{{ message }}</div>
    <section v-if="loading" class="card"><div class="loading-overlay"><div class="spinner" /></div></section>
    <template v-else-if="appointment">
      <section class="card" style="margin-bottom:20px"><div class="section-header"><div><h2>Consultation</h2><p class="text-muted">Dr. {{ appointment.doctor?.first_name }} {{ appointment.doctor?.last_name }} · {{ formatDate(appointment.scheduled_at) }}</p></div><span class="badge badge-blue">{{ workflowLabel }}</span></div><div class="summary-grid"><div><span>Motif</span><b>{{ appointment.reason_for_visit || '—' }}</b></div><div><span>Assurance</span><b>{{ insurance?.provider?.name || 'Aucune sélectionnée' }}</b></div><div><span>N° assuré</span><b>{{ insurance?.member_id || '—' }}</b></div><div><span>Statut</span><b>{{ appointment.status }}</b></div></div></section>
      <section v-if="!submitted" class="card"><h2>Votre partie</h2><p class="text-muted" style="margin-bottom:18px">Cette fiche est un modèle générique CareLink. Aucun formulaire INAM officiel n'est utilisé ici.</p><div class="form-group"><label class="form-label">Motif de consultation</label><textarea v-model="patientValues.reason_for_visit" class="input" rows="3" required /></div><div class="form-group"><label class="form-label">Informations utiles</label><textarea v-model="patientValues.patient_notes" class="input" rows="4" placeholder="Symptômes, allergies ou informations que vous souhaitez signaler au médecin…" /></div><div class="form-group" v-if="insurances.length"><label class="form-label">Choisir mon assurance</label><select v-model="insurance" class="input" @change="patientValues.insurance_member_id = insurance?.member_id || ''"><option v-for="item in insurances" :key="item.id" :value="item">{{ item.provider?.name }} — {{ item.member_id || item.policy_number || 'N° non renseigné' }}</option></select></div><div class="form-group"><label class="form-label">Numéro d’assuré</label><input v-model="patientValues.insurance_member_id" class="input" :placeholder="insurance?.member_id || 'Non renseigné'" /></div><button class="btn btn-primary" :disabled="saving" @click="saveAndSubmit">{{ saving ? 'Transmission…' : 'Enregistrer et transmettre au médecin' }}</button></section>
      <section v-else class="card"><div class="success-box"><div class="success-icon">✓</div><div><h2>Fiche transmise</h2><p>Votre partie est terminée. Le médecin pourra compléter les informations médicales avant la validation finale.</p></div></div><RouterLink to="/appointments" class="btn btn-ghost" style="margin-top:16px">Retour aux rendez-vous</RouterLink></section>
    </template>
    <section v-else class="card empty-state"><div class="empty-icon">📄</div><div class="empty-title">Rendez-vous introuvable</div><p>Ce rendez-vous n’est pas disponible pour la préparation d’une fiche.</p></section>
  </AppLayout>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'; import { RouterLink, useRoute } from 'vue-router'; import AppLayout from '@/components/layout/AppLayout.vue'; import { supabase } from '@/lib/supabase'; import { useAuthStore } from '@/stores/auth';
const route=useRoute(); const auth=useAuthStore(); const loading=ref(true); const saving=ref(false); const message=ref(''); const error=ref(false); const appointment=ref<any>(null); const insurances=ref<any[]>([]); const insurance=ref<any>(null); const submission=ref<any>(null); const patientValues=reactive({reason_for_visit:'',patient_notes:'',insurance_member_id:''}); const submitted=computed(()=>['patient_submitted','doctor_in_progress','completed'].includes(submission.value?.workflow_status)); const workflowLabel=computed(()=>({patient_draft:'À compléter',patient_submitted:'Transmise au médecin',doctor_in_progress:'Médecin en cours',completed:'Terminée'} as Record<string,string>)[submission.value?.workflow_status||'patient_draft']||'À compléter'); function formatDate(v:string){return new Date(v).toLocaleString('fr-FR')}
async function load(){if(!auth.user)return;const id=String(route.params.id);const a=await supabase.from('appointments').select('id,patient_id,doctor_id,scheduled_at,status,reason_for_visit,patient_notes,doctor:profiles!appointments_doctor_id_fkey(first_name,last_name)').eq('id',id).eq('patient_id',auth.user.id).single();appointment.value=a.data;if(a.error||!a.data){loading.value=false;return}const i=await supabase.from('patient_insurances').select('id,member_id,policy_number,provider:insurance_providers(id,name,code)').eq('patient_id',auth.user.id).eq('is_verified',true).order('created_at',{ascending:false});insurances.value=i.data||[];insurance.value=insurances.value[0]||null;const v=await supabase.from('insurance_form_versions').select('id,template:insurance_form_templates!insurance_form_versions_template_id_fkey(code,name)').eq('status','published').order('created_at',{ascending:false});const generic=(v.data||[]).find((x:any)=>x.template?.code==='CARELINK_GENERIC_CARE_SHEET')||v.data?.[0];if(!generic){message.value='Aucun modèle de fiche publié.';error.value=true;loading.value=false;return}const s=await supabase.from('insurance_form_submissions').select('*').eq('appointment_id',id).eq('patient_id',auth.user.id).order('created_at',{ascending:false}).limit(1).maybeSingle();submission.value=s.data;if(s.data?.patient_insurance_id)insurance.value=insurances.value.find((x:any)=>x.id===s.data.patient_insurance_id)||insurance.value;if(s.data?.patient_values)Object.assign(patientValues,s.data.patient_values);else{patientValues.reason_for_visit=a.data.reason_for_visit||'';patientValues.patient_notes=a.data.patient_notes||'';patientValues.insurance_member_id=insurance.value?.member_id||''}if(!s.data){const created=await supabase.from('insurance_form_submissions').insert({form_version_id:generic.id,patient_id:auth.user.id,patient_insurance_id:insurance.value?.id||null,appointment_id:id,status:'draft',workflow_status:'patient_draft',patient_values:{...patientValues},professional_values:{}}).select('*').single();submission.value=created.data}loading.value=false}
async function saveAndSubmit(){if(!submission.value?.id||!patientValues.reason_for_visit.trim()){message.value='Le motif de consultation est requis.';error.value=true;return}saving.value=true;message.value='';error.value=false;const u=await supabase.from('insurance_form_submissions').update({patient_values:{...patientValues}}).eq('id',submission.value.id).eq('patient_id',auth.user?.id).eq('workflow_status','patient_draft');if(u.error){error.value=true;message.value=u.error.message;saving.value=false;return}const r=await supabase.rpc('submit_insurance_form_by_patient',{p_submission_id:submission.value.id});if(r.error){error.value=true;message.value=r.error.message}else{submission.value=r.data;message.value='Fiche transmise au médecin.'}saving.value=false}onMounted(load);
</script>
<style scoped>.hero-gradient{padding:28px;border-radius:var(--radius-xl);background:linear-gradient(135deg,var(--color-primary-700),var(--color-primary-500));color:#fff}.hero-gradient h1,.hero-gradient p{color:#fff}.eyebrow{font-size:var(--font-size-xs);font-weight:800;letter-spacing:.08em;opacity:.8}.section-header{display:flex;justify-content:space-between;gap:16px;align-items:flex-start}.text-muted{color:var(--color-text-sub);font-size:var(--font-size-sm)}.summary-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px;margin-top:18px}.summary-grid div{display:flex;flex-direction:column;gap:4px;padding:12px;border-radius:var(--radius-md);background:var(--color-neutral-50)}.summary-grid span{font-size:var(--font-size-xs);color:var(--color-text-muted)}.form-group{display:flex;flex-direction:column;gap:7px;margin-bottom:16px}.success-box{display:flex;gap:16px;align-items:flex-start;padding:18px;border:1px solid var(--color-success-200);background:var(--color-success-50);border-radius:var(--radius-lg)}.success-icon{width:38px;height:38px;border-radius:50%;display:grid;place-items:center;background:var(--color-success-500);color:#fff;font-weight:800}@media(max-width:700px){.summary-grid{grid-template-columns:1fr}.section-header{flex-direction:column}}</style>
