<template>
  <AppLayout page-title="Autour de moi">
    <div class="card location-hero"><div><span class="eyebrow">LOCALISATION</span><h2>Hôpitaux et pharmacies proches</h2><p v-if="position">Position utilisée : {{ position.latitude.toFixed(5) }}, {{ position.longitude.toFixed(5) }}</p><p v-else>Autorisez la localisation pour trouver les établissements les plus proches de vous.</p></div><button class="btn btn-primary" :disabled="loading" @click="locate">{{ loading ? 'Recherche…' : 'Utiliser ma position' }}</button></div>
    <div v-if="error" class="card alert-error">{{ error }}</div>
    <div v-if="position" class="grid-2"><section class="card"><div class="section-head"><h3>🏥 Hôpital / centre de santé le plus proche</h3><span class="badge" v-if="facilities.length">{{ facilities[0].distance_km.toFixed(1) }} km</span></div><div v-if="facilities.length" class="nearby-list"><article v-for="f in facilities" :key="f.id" class="nearby-item"><div><b>{{ f.name }}</b><small>{{ facilityLabel(f.facility_type) }} · {{ f.address }}, {{ f.city }}</small><small v-if="f.phone">☎ {{ f.phone }}</small><span v-if="f.emergency_available" class="badge badge-green">Urgences</span></div><div class="nearby-actions"><strong>{{ formatDistance(f.distance_km) }}</strong><a class="btn btn-sm" :href="directions(f.latitude, f.longitude)" target="_blank" rel="noopener">Itinéraire</a></div></article></div><div v-else class="empty-state">Aucun établissement vérifié trouvé dans un rayon de 25 km.</div></section><section class="card"><div class="section-head"><h3>💊 Pharmacie la plus proche</h3><span class="badge" v-if="pharmacies.length">{{ pharmacies[0].distance_km.toFixed(1) }} km</span></div><div v-if="pharmacies.length" class="nearby-list"><article v-for="p in pharmacies" :key="p.id" class="nearby-item"><div><b>{{ p.name }}</b><small>{{ p.address }}, {{ p.city }}</small><small v-if="p.phone">☎ {{ p.phone }}</small><span v-if="p.is_duty_pharmacy" class="badge badge-green">Pharmacie de garde</span></div><div class="nearby-actions"><strong>{{ formatDistance(p.distance_km) }}</strong><a class="btn btn-sm" :href="directions(p.latitude, p.longitude)" target="_blank" rel="noopener">Itinéraire</a></div></article></div><div v-else class="empty-state">Aucune pharmacie vérifiée trouvée dans un rayon de 25 km.</div></section></div>
  </AppLayout>
</template>
<script setup lang="ts">
import { ref } from 'vue';
import AppLayout from '@/components/layout/AppLayout.vue';
import { getCareLinkClient, LocationService } from '@carelink/supabase-client';
import { formatDistance } from '@carelink/shared';
const client = getCareLinkClient(); const service = new LocationService(client); const loading = ref(false); const error = ref(''); const position = ref<{ latitude:number; longitude:number } | null>(null); const facilities = ref<any[]>([]); const pharmacies = ref<any[]>([]);
function facilityLabel(type:string){return ({hospital:'Hôpital',clinic:'Clinique',health_center:'Centre de santé',maternity:'Maternité',laboratory:'Laboratoire'} as Record<string,string>)[type]||'Établissement de santé';}
function directions(lat:number,lon:number){return `https://www.google.com/maps/dir/?api=1&destination=${lat},${lon}`;}
async function locate(){loading.value=true;error.value='';try{const pos=await LocationService.browserPosition();position.value={latitude:pos.coords.latitude,longitude:pos.coords.longitude};[facilities.value,pharmacies.value]=await Promise.all([service.getNearbyHealthFacilities(pos.coords.latitude,pos.coords.longitude),service.getNearbyPharmacies(pos.coords.latitude,pos.coords.longitude)]);}catch(e:any){error.value=e?.message||'Impossible de récupérer votre position.';}finally{loading.value=false;}}
</script>
<style scoped>.location-hero{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:16px}.eyebrow{font-size:11px;font-weight:700;letter-spacing:.08em}.section-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.nearby-list{display:grid;gap:10px}.nearby-item{display:flex;justify-content:space-between;gap:16px;padding:14px;border:1px solid #e5e7eb;border-radius:12px}.nearby-item small{display:block;margin-top:4px;color:#64748b}.nearby-actions{display:flex;flex-direction:column;align-items:flex-end;gap:8px;white-space:nowrap}.alert-error{margin-bottom:16px;border-left:4px solid #dc2626}.btn-sm{padding:7px 10px;font-size:12px}@media(max-width:800px){.location-hero,.nearby-item{flex-direction:column}.nearby-actions{align-items:flex-start}}</style>
